# Docker Build and Push
# https://learn.microsoft.com/en-us/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

jobs:
- job: BuildAndPush
  displayName: Build and Push Docker Image
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: Docker@2
    displayName: Build and Push Image
    inputs:
      containerRegistry: 'acr66'   # Service Connection name in Azure DevOps
      repository: 'your-repo-name' # Name of your image in ACR
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
      tags: |
        $(tag)
